/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KanbanCard: typeof import('./src/components/kanban/Kanban-Card.vue')['default']
    KanbanList: typeof import('./src/components/kanban/Kanban-List.vue')['default']
    ModalNewProject: typeof import('./src/components/Modal-NewProject.vue')['default']
    ModalProject: typeof import('./src/components/project/Modal-Project.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewProject: typeof import('./src/components/project/New-Project.vue')['default']
    ProjectCard: typeof import('./src/components/project/Project-Card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
